### ISSUE TITLE
Make show(...) raise exceptions on invalid parameter values, instead of silently changing their values

### ISSUE THREAD

**Issue by joostit** [samveen/pico-oled-1.3-driver#10]
Make changes to not 'silently try to fix' invalid parameters in the Show(...) method. In my experience this will hide bugs in other parts of the application and make debugging more difficult. I propose to raise IndexErrors (e.g.) when wrong parameter values are given.

I will create a pull request for this in the coming days.

As discussed in: https://github.com/samveen/pico-oled-1.3-driver/issues/8#issuecomment-2050956576

**Comment by samveen** [comment]
I've been thinking on how I can use this, have the following observations.

- All manipulations to the display happen via the underlying Framebuffer base class of the display.
- Most of my updates are using `text()`, `ellipse()` or `rect()` , with a few `fill()` to clear the screen.
- A `fill()` corresponds to a full screen `show()` with no parameters, writing the complete buffer to the display.
- A call to `rect()` to simulate the `fill()` call for the Pico oled 1.3 is `rect(0,0,128,64,0xffff,True)`
- The coordinates are `(0,0)` at the top left of the screen  and `(width,height)` at the bottom right.

With this in mind, I imagine that the `show()` should use an equivalent parameter system as the others.

**Comment by joostit** [comment]
> * The coordinates are `(0,0)` at the top left of the screen  and `(width,height)` at the bottom right.
> 
> With this in mind, I imagine that the `show()` should use an equivalent parameter system as the others.

I fully agree. At some point it otherewise gets pretty confusing when mixing up framebuffer coordinates with the display columns, segments and pages and their dynamic memory mappings. I'll change the parameter list order for the  __validateShowArguments(...) method.

One question: The maximum EndY value could either be '63' (updates including the last index) or '64' (updates excluding the last number). What's the convention in Python and what would you prefer @samveen ?

**Comment by samveen** [comment]
Using `rect()` as the reference, which uses the format: 
- Beginning coordinates (`x`,`y`) - this ranges from (`0`,`0`) to (`self.width-1`,`self.height-1`)
- Delta from beginning (`w`,`h`) - this ranges from (`1`,`1`) to (`self.width`,`self.height`)

Actual ending coordinates will need to be rounded down in case `x+w` or `y+h` are greater than the dimensions of the screen. I'll check the behaviour of `rect()` on out-of-bounds coordinates.

**Comment by joostit** [comment]
Although I do agree with you, as explained in #8, I'll continue along a different route to suit my specific use case. Feel free to close this issue and discard or cherry pick the pull request :)
