### ISSUE TITLE
'text()' function speed can be improved with 'blit()'

### ISSUE THREAD

**Issue by mungewell** [samveen/pico-oled-1.3-driver#3]
The `text()` call is a LOT slower than the original lib... for example.
```
import utime

if __name__ == "__main__":
    display = OLED_1inch3_SPI()

    start = utime.ticks_ms()
    c = 0
    while c < 1000:
        display.text("PicoOled-1.3 Demo", 50, 0, 1)#, False)
        c=c+1
    
    display.text(str(utime.ticks_diff(utime.ticks_ms(), start)), 0, 30)
    display.show()
```

Original completes in 294ms, this modified lib (with `pixel()`) takes 10012ms.... Obviously the fancier font would come at a cost.

This can be improved with `blit()`. Blitting each character completes in 4712ms, combining to a single blit for whole phrase completes in 3662ms, or actually a little bit faster if we implement clipping at screen edge.

I'll prepare a pull request. :-)

**Comment by samveen** [comment]
- That's a huge improvement.
- Was the performance metric for `BasicFont` or for `BasicFontCondensed`?
- Would you add the figure for the font not tested yet?
- Does the improvement factor in the improvements to `.show()` (#2) or without the improvements?

I would love to see comparison times for the 4 different options, only if you have the time and patience.

**Comment by mungewell** [comment]
The demo code is attached to the ticket, you can use this to validate. I just tagged it on the the end of library to test, metric was printing the same message 1000 times and recording the time taken.

I presume it was the condensed font (I didn't change/set anything).

Patch is standalone, does not need the `show()` fix. Was tested without.

**Comment by mungewell** [comment]
I added more functionality:
- Improved wrap - either to left of screen, or X0 co-ordinate
- Stop drawing below bottom of screen - gives slight speed increase
- Text Justification - Right, Left, or Centered. Triggered when text hits left/right of screen.

These are controlled with extra parameters, but default (unspecified) behaviour is as per your original mods.
`text(self,s,x0,y0,col=0xffff,wrap=1,just=0)`
